# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 687362932690405a04b21b61e92f66fd513568ee22fb9743bee0f056661c9abf037d0df307b87283ff5188ac360c58b67eb692c0f45a42fd4656dd4f9f4daf1d

test:
  secret_key_base: 11de7afd4ef0d36c5d8982c64487b52cf98a520e280a445f2ca99fdafdc37aca920ca9cf3741040167915535c768d626527843c68ddae7d48f50ed1cfbd50626

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
